language: ruby
services:
  - mysql
rvm:
 - 2.3.1
 - 2.4.0
 - 2.5.0
 
gemfile:
  - gemfiles/rails_5.2.1.gemfile
  - gemfiles/rails_5.2.3.gemfile

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS myapp_test;'
before_script:
  - cp ./spec/dummy/config/database.yml.test ./spec/dummy/config/database.yml
  - bundle exec rails db:migrate RAILS_ENV=test

matrix:
  include:
  - rvm: 2.3.1
    gemfile: gemfiles/rails_5.2.1.gemfile
  - rvm: 2.3.8
    gemfile: gemfiles/rails_5.2.3.gemfile
  - rvm: 2.5.0
    gemfile: gemfiles/rails-6.gemfile


script: COVERALLS_REPO_TOKEN=bPQteZngJWF84BYuws90hMmXwWYcMpV9S bundle exec rspec

#after_script:
#  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT